class TestData:
    Chrome_driver_Path = "C:\\Users\g.dnyandeo.bhosale\Desktop\Automation Testing\Drivers\chromedriver.exe"
    Firefox_driver_Path = "C:\\Users\g.dnyandeo.bhosale\Desktop\Automation Testing\Drivers\geckodriver.exe"
    Edge_driver_path = "C:\\Users\g.dnyandeo.bhosale\Desktop\Automation Testing\Drivers\msedgedriver.exe"

    BASE_URL = "https://www.saucedemo.com"
    HOME_PAGE_URL = "https://www.saucedemo.com/inventory.html"
    SCREENSHOT_PATH = "\\Users\g.dnyandeo.bhosale\PycharmProjects\E_Commerce_SwagLabs\Screenshots"
    USERNAME = "standard_user"
    PASSWORD = "secret_sauce"
    LOGIN_PAGE_TITLE = "Swag Labs"
    HOME_PAGE_TITLE = "Swag Labs"
    HEADER = "Products"
    ITEM_NAME = "Sauce Labs Fleece Jacket"

    FIRST_NAME = "Ganesh345"
    LAST_NAME = "Bhosale456"
    POSTAL_CODE = "414208"
    CONFIRM_MSG = "THANK YOU FOR YOUR ORDER"

    """ DDT Login Page Data """
    LOGIN_DDT_URL = "https://practicetestautomation.com/practice-test-login/"
    LOGIN_DDT_TITLE = "Logged In Successfully | Practice Test Automation"
    LOGGED_IN_URL = "https://practicetestautomation.com/logged-in-successfully/"
    LOGINDATA_FILENAME = "C:\\Users\g.dnyandeo.bhosale\PycharmProjects\E_Commerce_SwagLabs\TestData\LoginData.xlsx"
    LOGINDATA_SHEETNAME = "LoginData"
